In [112]:
import pandas as pd
import numpy as np

In [113]:
df = pd.read_csv("Dataset/cleaned_data1.csv")
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Absences,HireYear,HireMonth,HireDay,HireMonthName,HireDayName,SalaryLabel,Salary_Num,Sal1,Sal2
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,1,2011,7,5,July,Tuesday,Low Salary,0,Low,Salary
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,17,2015,3,30,March,Monday,Average Salary,1,Average,Salary
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,3,2011,7,5,July,Tuesday,Low Salary,0,Low,Salary
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,15,2008,1,7,January,Monday,Low Salary,0,Low,Salary
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,2,2011,7,11,July,Monday,Low Salary,0,Low,Salary

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
 36  HireYear                    311 non-null    int64
 37  HireMonth                   311 non-null    int64
 38  HireDay                     311 non-null    int64
 39  HireMonthName               311 non-null    object
 40  HireDayName                 311 non-null    object
 41  SalaryLabel                 311 non-null    object
 42  Salary_Num                  311 non-null    int64
 43  Sal1                        311 non-null    object
 44  Sal2                        311 non-null    object
dtypes: float64(1), int64(21), object(23)
memory usage: 109.5+ KB

In [115]:
# find total employees working in departments.
df['Department'].value_counts()

Department
Production              209
IT/IS                    50
Sales                    31
Software Engineering     11
Admin Offices             9
Executive Office          1
Name: count, dtype: int64

In [116]:
# group by (categorical) + 
    #   aggregate function (categorical, continues,continues,discrete) 
        #   -> used in analysis
# aggregate function only -> used in KPIs (mean, min, max, count, sum)

In [117]:
emp_dep = df.groupby('Department')['EmpID'].count().reset_index().rename(
    columns = {
        'EmpID': 'Total_Employees'
    }
).sort_values(
    by = 'Total_Employees', ascending = False, ignore_index = True)
emp_dep

             Department  Total_Employees
0            Production              209
1                 IT/IS               50
2                 Sales               31
3  Software Engineering               11
4         Admin Offices                9
5      Executive Office                1

In [118]:
# find total salary distributed to each employee by their job position.

In [119]:
pos_sal = df.groupby('Position')['Salary'].sum().reset_index()
pos_sal.head()

                   Position   Salary
0              Accountant I   190523
1  Administrative Assistant   156840
2        Area Sales Manager  1753179
3              BI Developer   381860
4               BI Director   110929

In [120]:
pos_sal['Salary'] = pos_sal['Salary'].map("Rs.{:,.2f}".format)
pos_sal.head()

                   Position           Salary
0              Accountant I    Rs.190,523.00
1  Administrative Assistant    Rs.156,840.00
2        Area Sales Manager  Rs.1,753,179.00
3              BI Developer    Rs.381,860.00
4               BI Director    Rs.110,929.00

In [121]:
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f"{prefix}""{:,.2f}".format)

In [122]:
emp_pos_details = df.groupby('Position').agg(
    Total_Salary = ('Salary', 'sum'),
    Total_Employees = ('EmpID', 'count'),
    Max_Salary = ('Salary', 'max'),
    Min_Salary = ('Salary', 'min'),
    Avg_Salary = ('Salary', 'mean')
).reset_index()
emp_pos_details.columns = emp_pos_details.columns.str.replace('_', ' ')

currencyConverter(emp_pos_details, 'Rs.', 'Total Salary', 'Max Salary',
                  'Min Salary', 'Avg Salary')

emp_pos_details.head()

,Position,Total Salary,Total Employees,Max Salary,Min Salary,Avg Salary
0,Accountant I,"Rs.190,523.00",3,"Rs.64,520.00","Rs.63,000.00","Rs.63,507.67"
1,Administrative Assistant,"Rs.156,840.00",3,"Rs.55,000.00","Rs.49,920.00","Rs.52,280.00"
2,Area Sales Manager,"Rs.1,753,179.00",27,"Rs.74,326.00","Rs.55,875.00","Rs.64,932.56"
3,BI Developer,"Rs.381,860.00",4,"Rs.99,020.00","Rs.90,100.00","Rs.95,465.00"
4,BI Director,"Rs.110,929.00",1,"Rs.110,929.00","Rs.110,929.00","Rs.110,929.00"